security:

    encoders:
        App\Document\User:
            algorithm: bcrypt
            cost: 12

    providers:
        user:
            mongodb: {class: App\Document\User, property: username}
        environment:
            mongodb: {class: App\Document\Environment, property: id}
        all:
            chain:
                providers: [environment, user]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        composer:
            pattern: ^/(packages.json|p/)
            provider: all
            guard:
                authenticators:
                    - App\Security\ComposerAuthenticator

        main:
            anonymous: true
            provider: user
            guard:
                authenticators:
                    - App\Security\FormAuthenticator
                    - App\Security\GitlabAuthenticator
                entry_point: App\Security\FormAuthenticator

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
